services:
  crawler_librerias:
    build:
      context: ./IntegracionLibrerias
      dockerfile: Dockerfile.final

    restart: "no"

    command: ["python", "-m", "crawler_rit.ciclo"]

    environment:
      RIT_CONFIG_PATH: /config/settingsCrawler.json
      RIT_REPOSITORY_ROOT: /repositorio
      PGHOST: postgres
      PGPORT: "5432"
      PGDATABASE: TheSearcher
      PGUSER: admin
      PGPASSWORD: "123"

    volumes:
      - ./config:/config:ro
      - ./IntegracionLibrerias/datos:/app/datos
      - ./IntegracionLibrerias/logs:/app/logs
      - ./IntegracionPropia/datos:/repositorio/IntegracionPropia/datos