services:
  app:
    build:
      context: ./TheSearcher
      dockerfile: Dockerfile
    container_name: node_app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./TheSearcher/:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development



  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: TheSearcher
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  crawler_librerias:
    build:
      context: ./IntegracionLibrerias
      dockerfile: Dockerfile
    restart: "no"
    environment:
      RIT_CONFIG_PATH: /config/settingsCrawler.json
      PGHOST: postgres
      PGPORT: "5432"
      PGDATABASE: TheSearcher
      PGUSER: admin
      PGPASSWORD: "123"
    volumes:
      - ./config/settingsCrawler.json:/config/settingsCrawler.json:ro
      - ./IntegracionLibrerias/datos:/app/datos
      - ./IntegracionLibrerias/logs:/app/logs
    command: ["python", "-m", "scrapy", "version"]

volumes:
  postgres_data:
