services:
  app:
    build: .
    container_name: node_app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./TheSearcher/:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development



  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: TheSearcher
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
