FROM python:3.14-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1
WORKDIR /app
COPY requirements.txt requirements-final.txt ./
RUN python -m pip install -r requirements-final.txt
COPY . .
CMD ["python", "-m", "crawler_rit.ciclo"]
